### ISSUE TITLE
Windows trouble installing with pip 

### ISSUE THREAD

**Issue by johnhill2424** [ktrueda/parquet-tools#13]
![2021-07-20 10_48_37-Windows trouble installing with pip · Issue #13 · ktrueda_parquet-tools](https://user-images.githubusercontent.com/32116706/126345116-315d30e1-1517-4740-9590-64e86670d357.png)
Having an issue installing parquet-tools on Windows. Keep getting this error. Do I need Python version < 3.7?

**Comment by ktrueda** [comment]
@johnhill2424 Thank you for making issue.
But I'm sorry for not giving sure advice about WIndows because of not having windows machine.

I believe that pip installed numpy==1.16.0 but the numpy version does not support 3.9(your python env).

see https://pypi.org/project/numpy/1.16.0/

I thought that you could install parquet-tools if you installed latest numpy. So please run `poetry add numpy` before installing parquet-tools.

If it will work in your Windows machine, please make PR.
